apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    name: api-node
  name: api-node
spec:
  replicas: 3
  template:
    metadata:
      labels:
        name: api-node
    spec:
      containers:
      - image: us.gcr.io/akka-api-template/api:f8abd20
        name: api-node
        ports:
        - containerPort: 8080
