apiVersion: v1
kind: Service
metadata:
  labels:
    name: api-service
  name: api-service
spec:
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  selector:
    name: api-node
  type: LoadBalancer