package com.akkaapitemplate.infrastructure.routes

import com.akkaapitemplate.infrastructure.serialization.ApplicationMarshalling

trait ApplicationRoute extends ApplicationMarshalling with RequestIdDirective
